### ISSUE TITLE
Request: Linux version.

### ISSUE THREAD

**Issue by Git-Forked** [kuesji/link_eye#1]
Would it be possible you could make a Linux version of this app, preferably not using java language.  
I find your Android app very useful, and would like to have an equivalent on my Linux systems.  
Thank you.

**Comment by kuesji** [comment]
currently it is not on my roadmap. things will change in the future but i say "no" at the moment.

**Comment by Efreak** [comment]
This isn't really hard to do at all. I've got a basic script hacked together [here](https://gist.github.com/Efreak/d476e40c0db348edd626f78e0ae15009#file-open-edited-url-sh). Change it to open with `xdg-open --chooser` if you want to pick what browser, or use sensible-browser, or modify the list of browsers in the script. Alternatively, you could use another dialog to set up a [radio list](https://github.com/JazerBarclay/whiptail-examples#radio-list). If you don't like whiptail, there's also `zenity`, `(k|x|gtk)?dialog`, `yad`, or [`read`](https://askubuntu.com/a/1386907).

**Comment by kuesji** [comment]
porting this to linux isn't hard but getting it to work consistently is hard.
default apps not protected on linux unlike android because of lack of proper sandbox on desktop and this leads to inconsistent behaviour on this kind of app. 
i don't like the idea of firefox/chromium popping instead of link eye due firefox/chromium messed with defaults. 

otherwise i'll write a small gui application with c/gtk easily, not half-baked shellscript with whiptail,zenity or something like them.

**Comment by Git-Forked** [comment]
> This isn't really hard to do at all. I've got a basic script hacked together [here](https://gist.github.com/Efreak/d476e40c0db348edd626f78e0ae15009#file-open-edited-url-sh). Change it to open with `xdg-open --chooser` if you want to pick what browser, or use `sensible-browser`, or modify the list of browsers in the script. Alternatively, you could use another dialog to set up a [radio list](https://github.com/JazerBarclay/whiptail-examples#radio-list). If you don't like whiptail, there's also `zenity`, `(k|x|gtk)?dialog`, `yad`, or [`read`](https://askubuntu.com/a/1386907).

Thanks @Efreak
I'll check out your script when I next get a free day to fool around on the computer.
