### ISSUE TITLE
Sort by most frequently used

### ISSUE THREAD

**Issue by Atemu** [kuesji/link_eye#4]
Hi, I came across your app in an attempt to unfuck Android 12's user-unfriendly link handling behaviour.

On Android 11 and previous versions, the "open in" menu would show apps that can open the given link which I'm trying to replicate now.

This menu was sorted by most frequently used or most accessed (either would be fine by me) but link_eye sorts alphabetically instead. This means I need to scroll through a list of browsers to find the "Slide" or NewPipe apps down in the list which is fiddly and annoying.

It would be better to sort them by how frequently they have been used instead or at least give the option to.

**Comment by kuesji** [comment]
hmm. i heard that hostile behaviour of android 12 but didn't saw yet because i'm still using android 9 ( nokia 3 ).
this request is not a bad idea but i'm used to alphabetical sorting and i'm not into to recently used apps.
so, i can't spend my free time to things doesn't benefits to me.

( i developed this app for myself and just shared to public. )

**Comment by Atemu** [comment]
I understand, thanks. 

For anyone who also needs this feature because of Android 12, I have found an alternative which implements this feature (and more) at https://github.com/tasomaniac/OpenLinkWith
